//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serviceProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agenda
    {
        public string Servico { get; set; }
        public string Horario { get; set; }
        public string Telefone { get; set; }
    }
}
